"""auth

Revision ID: af65f8122a88
Revises: 066c85ff0d14
Create Date: 2025-07-19 11:56:26.052763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af65f8122a88'
down_revision: Union[str, Sequence[str], None] = '066c85ff0d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('image', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'image')
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
