"""change dt to int

Revision ID: e4df0c330215
Revises: 99355d30ae64
Create Date: 2025-07-19 20:35:41.708139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4df0c330215'
down_revision: Union[str, Sequence[str], None] = '99355d30ae64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('sessions', 'expires',
    #            existing_type=postgresql.TIMESTAMP(),
    #            type_=sa.Integer(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE sessions
        ALTER COLUMN expires
        TYPE INTEGER
        USING EXTRACT(EPOCH FROM expires)::INTEGER
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('sessions', 'expires',
    #            existing_type=sa.Integer(),
    #            type_=postgresql.TIMESTAMP(),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    op.alter_column(
        'sessions',
        'expires',
        existing_type=sa.Integer(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False
    )
